apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
data:
  database_url: mongodb-statefulset-0.mongodb-svc

# rs.initiate({ _id: "MainRepSet", version: 1,
#  memebers: [
#    { _id: 0, host: "mongodb-statefulset-0.mongodb-svc.default.svc.cluster.local:27017" },
#    { _id: 1, host: "mongodb-statefulset-1.mongodb-svc.default.svc.cluster.local:27017" },
#    { _id: 2, host: "mongodb-statefulset-2.mongodb-svc.default.svc.cluster.local:27017" }] });